f = open("encrypt.txt")
es = f.read()
f.close()
s = "ALAN TURING, AN ENGLISH MATHEMATICIAN, LOGICIAN, AND CRYPTANALYST, WAS A COMPUTER PIONEER. OFTEN REMEMBERED FOR HIS CONTRIBUTIONS TO THE FIELDS OF ARTIFICIAL INTELLIGENCE AND MODERN COMPUTER SCIENCE (BEFORE EITHER EVEN EXISTED), TURING IS PROBABLY BEST KNOWN FOR WHAT IS NOW DUBBED THE \"TURING TEST.\" IT IS A PROCESS OF TESTING A MACHINES ABILITY TO \"THINK.\"  THE BASIC PREMISE OF THE TURING TEST IS THAT A HUMAN JUDGE WOULD BE PLACED IN ISOLATION AND HAVE TWO CONVERSATIONS - ONE WITH A COMPUTER AND ONE WITH ANOTHER PERSON - EXCEPT THE JUDGE WOULDN'T BE TOLD WHICH WAS WHICH. IF THE COMPUTER COULD FOOL THE JUDGE AND CARRY ON A CONVERSATION THAT IS INDISTINGUISHABLE FROM THAT OF THE HUMAN, THE COMPUTER IS SAID TO HAVE PASSED THE TURING TEST. NO COMPUTER HAS PASSED IT YET. LESS IS KNOWN, HOWEVER, ABOUT TURING'S INTELLIGENCE WORK DURING WWII WHEN HE USED HIS MATHEMATICAL AND CRYPTOLOGIC SKILLS TO HELP BREAK ONE OF THE MOST DIFFICULT OF GERMAN CIPHERS, ENIGMA. ENIGMA WAS A CIPHER MACHINE, EACH KEYSTROKE REPLACED A CHARACTER IN THE MESSAGE WITH ANOTHER CHARACTER DETERMINED BY THE MACHINES ROTOR SETTINGS AND WIRING ARRANGEMENTS THAT WERE PREVIOUSLY ESTABLISHED BETWEEN THE SENDER AND THE RECEIVER. IN THE EARLY YEARS OF WWII, TURING WORKED AT BRITAINS CODE BREAKING HEADQUARTERS IN BLETCHLEY PARK. IN ADDITION TO MATHEMATICIANS, BLETCHLEY PARK ALSO RECRUITED LINGUISTS AND CHESS CHAMPIONS, AND ATTRACTED TALENT BY APPROACHING WINNERS OF A COMPLEX CROSSWORD PUZZLE TOURNAMENT HELD BY THE DAILY TELEGRAPH.  TURING'S MATHEMATICAL AND LOGIC SKILLS MADE HIM A NATURAL CRYPTANALYST. WHEREAS CRYPTOGRAPHERS WRITE ENCRYPTION SYSTEMS, AND CRYPTOLOGISTS STUDY THEM, CRYPTANALYSTS LIKE TURING BREAK THEM. IN 1939, TURING CREATED A METHOD CALLED \"THE BOMBE,\" AN ELECTROMECHANICAL DEVICE THAT COULD DETECT THE SETTINGS FOR ENIGMA, ALLOWING THE ALLIED POWERS TO DECIPHER GERMAN ENCRYPTIONS."
a = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
        ' ', '.', ',', ';', '!', '?', '(', ')', '-', '\'', '"']
print(len(a))
def encrypt(a, s, r1 = 0, r2 = 47):
    e = 0
    string = ""
    for chr in s:
            e = (a.index(chr) + r1 + r2) % len(a)
            string += a[e]
            r1 += 1
            if r1 % len(a) == len(a) - 1:
                r2 += 1

    return string

print()

tup = (-1, -1)

for p in range(len(a)):
    for q in range(len(a)):
        if(encrypt(a, s, p, q) == es):
            tup = (p, q)

print(tup)
#4, 11 